#version 450

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) readonly buffer Targets
{
    uint values[];
} targets;

layout(set = 0, binding = 1, std430) buffer Counters
{
    uint values[];
} counters;

layout(push_constant) uniform Parameters
{
    uint elementCount;
} parameters;

void main()
{
    const uint index = gl_GlobalInvocationID.x;
    if (index >= parameters.elementCount)
    {
        return;
    }

    atomicAdd(counters.values[targets.values[index]], 1U);
}
